services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend

  backend:
    build: ./backend
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
      - frontend
      - backend

  mongo:
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mongo_data:
