services:
  frontend:
    image: 413816840602.dkr.ecr.ap-south-1.amazonaws.com/week4-ui:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend

  backend:
    image: 413816840602.dkr.ecr.ap-south-1.amazonaws.com/week4-api:latest
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
      - frontend
      - backend

  mongo:
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mongo_data:
